### ISSUE TITLE
Permitir que um anúncio seja de aluguel e/ou venda

### ISSUE THREAD

**Issue by danigpam** [zebolinha80/PFC-Imobiliaria#3]
Permitir que um anúncio seja de aluguel e/ou venda
Além do valor de venda/aluguel, também acrescentar os campos de IPTU e condomínio no anúncio.

**Comment by DiegoGPereira** [comment]
Commit - 273dd1c

Adicionado os campos solicitados no agendamento, 
melhorado a usabilidade do filtro avançado agora o mesmo passa a utilizar AJAX (XMLHttpRequest)
O filtro agora utiliza hashmap para ir adicionando os where na query sql dinamicamente.
